// Generated by Structorizer 3.32-34 

using System;

/// <summary>
/// </summary>
public class 02_Prüfen_ob_zahl_gerade_oder_ungerade_ist
{

	/// <param name="args"> array of command line arguments </param>
	public static void Main(string[] args)
	{

		// TODO: Check and accomplish variable declarations: 
		??? zahl;

		// TODO: You may have to modify input instructions, 
		//       possibly by enclosing Console.ReadLine() calls with 
		//       Parse methods according to the variable type, e.g.: 
		//          i = int.Parse(Console.ReadLine()); 

		Console.Write("Bitte eine zahl angeben"); ,zahl = Console.ReadLine();
		if (zahl %2==0)
		{
			Console.WriteLine("Gerade");
		}
		else
		{
			Console.WriteLine("Ungerade");
		}
	}

}
