// Generated by Structorizer 3.32-34 

using System;

/// <summary>
/// </summary>
public class 02_26-02-06
{
 
	/// <param name="args"> array of command line arguments </param>
	public static void Main(string[] args)
	{

		// TODO: Check and accomplish variable declarations: 
		??? name;

		// TODO: You may have to modify input instructions, 
		//       possibly by enclosing Console.ReadLine() calls with 
		//       Parse methods according to the variable type, e.g.: 
		//          i = int.Parse(Console.ReadLine()); 

		// abfrage wie heißen sie 
		Console.Write("Wie Heißen Sie?"); ,name = Console.ReadLine();
		// Output mit namen 
		Console.Write("Hallo "); Console.WriteLine(name);
	}

}
