// Generated by Structorizer 3.32-34 

using System;

/// <summary>
/// </summary>
public class 06b_26-02-06
{

	/// <param name="args"> array of command line arguments </param>
	public static void Main(string[] args)
	{

		// TODO: Check and accomplish variable declarations: 
		??? A;

		// TODO: You may have to modify input instructions, 
		//       possibly by enclosing Console.ReadLine() calls with 
		//       Parse methods according to the variable type, e.g.: 
		//          i = int.Parse(Console.ReadLine()); 

		// erste zahl 
		Console.Write("Nennen Sie eine zahl:"); , A = Console.ReadLine();
		if (A == 0)
		{
			Console.WriteLine("Zahl ist 0");
		}
		else if (A > 0)
		{
			Console.WriteLine("Zahl ist Positiv");
		}
		else
		{
			Console.WriteLine("Zahl ist Negativ");
		}
	}

}
