// Generated by Structorizer 3.32-34 

using System;

/// <summary>
/// </summary>
public class 08_26-02-06
{

	/// <param name="args"> array of command line arguments </param>
	public static void Main(string[] args)
	{

		// TODO: Check and accomplish variable declarations: 
		??? zahl;

		// TODO: You may have to modify input instructions, 
		//       possibly by enclosing Console.ReadLine() calls with 
		//       Parse methods according to the variable type, e.g.: 
		//          i = int.Parse(Console.ReadLine()); 

		Console.Write("Bitte eine Zahl eingeben :)"); zahl = Console.ReadLine();
		while (zahl < 10)
		{
			Console.Write("Gebe neue Zahl ein"); zahl = Console.ReadLine();
		}
		Console.WriteLine("Fertig");
	}

}
