// Generated by Structorizer 3.32-34 

using System;

/// <summary>
/// select-fall
/// </summary>
public class 07_26-02-06
{

	/// <param name="args"> array of command line arguments </param>
	public static void Main(string[] args)
	{

		// TODO: Check and accomplish variable declarations: 
		double Ticketpreis;
		??? Fall;

		// TODO: You may have to modify input instructions, 
		//       possibly by enclosing Console.ReadLine() calls with 
		//       Parse methods according to the variable type, e.g.: 
		//          i = int.Parse(Console.ReadLine()); 

		Ticketpreis = 50.0;
		Console.WriteLine("Das Ticket kostet 50€");
		Console.Write("Sind sie Kinder, Schüler, oder erwachsen?"); , Fall = Console.ReadLine();
		switch (Fall)
		{
		case "Kinder":
			Console.Write("Für Kinder kostet das Ticket: "); Console.WriteLine(Ticketpreis-(Ticketpreis*20/100));
			break;
		case "Schüler":
			Console.Write("Für Schüler kostet das Ticket: "); Console.WriteLine(Ticketpreis-(Ticketpreis*15/100));
			break;
		case "Senioren":
			Console.Write("Für Senioren kostet das Ticket: "); Console.WriteLine(Ticketpreis-(Ticketpreis*10/100));
			break;
		default:
			Console.Write("Der Ticketpreis ist: "); Console.WriteLine(Ticketpreis);
		}
	}

}
