// Generated by Structorizer 3.32-34 

using System;

/// <summary>
/// </summary>
public class 04_Celsius_zu_fahrenheit_umrechner
{

	/// <param name="args"> array of command line arguments </param>
	public static void Main(string[] args)
	{

		// TODO: Check and accomplish variable declarations: 
		??? Temp;

		// TODO: You may have to modify input instructions, 
		//       possibly by enclosing Console.ReadLine() calls with 
		//       Parse methods according to the variable type, e.g.: 
		//          i = int.Parse(Console.ReadLine()); 

		Console.Write("Bitte gebe eine temperatur in grad Celsius ein"); Temp = Console.ReadLine();
		Console.Write("die temperatur von "); Console.Write(Temp); Console.Write("°C sind "); Console.Write(Temp+1.8+32); Console.WriteLine(" farenheit");
	}

}
