// Generated by Structorizer 3.32-34 

using System;

/// <summary>
/// </summary>
public class ???
{

	/// <param name="args"> array of command line arguments </param>
	public static void Main(string[] args)
	{

		// TODO: Check and accomplish variable declarations: 
		string b;
		string a;

		Console.WriteLine("Hello world");
		a = "BITLC";
		Console.WriteLine("My aprenticeshipment is at the "+a+". The "+ a +" is known for the quality of the lessons. "+ a +" is located in Neuss, Germany.");
		b = "hello ";
		Console.WriteLine(uppercase(b));
		Console.WriteLine(lowercase(b));
		Console.WriteLine(b+b);
		Console.Write(copy(b, 1,2)); Console.WriteLine(copy(b, 1,2));
		Console.Write(b); Console.WriteLine("world");
	}

}
