// Generated by Structorizer 3.32-34 

/**
 */
public class Arrays
{

	/**
	 * @param args
	 */
	public static void main(String[] args)
	{
		
		// TODO: Check and accomplish variable declarations: 
		int temp;
		int sum;
		int maximum;
		int[] array2;
		int[] array1;
		int arlen2;
		int arlen;

		array1 = new int[]{4, 5, 60, 7, 8, 10};
		arlen = length(array1);
		array2 = new int[]{0};
		for (int arpos = 0; arpos <= arlen-1; arpos += (1))
		{
			array2[arpos] = array1[arpos];
		}
		arlen2 = length(array2);
		maximum = array1[0];
		System.out.println("Array 1; Array 2 ");
		for (int arpos = 0; arpos <= arlen-1; arpos += (1))
		{
			System.out.println((array1[arpos]) + (";         ") + (array2[arpos]));
		}
		sum = 0;
		for (int arpos = 0; arpos <= arlen-1; arpos += (1))
		{
			sum = sum+array1[arpos];
		}
		System.out.println(("The sum of all array elements is: ") + (sum));
		for (int arpos = 0; arpos <= arlen-1; arpos += (1))
		{
			if (array1[arpos] > maximum)
			{
				maximum = array1[arpos];
			}
		}
		System.out.println(("The highest value in the array is: ") + (maximum));
		for (int i = 0; i <= arlen-1; i += (1))
		{
			for (int j = 0; j <= arlen-1; j += (1))
			{
				if (j<arlen-1)
				{
					if (array1[j]>array1[j+1])
					{
						temp = array1[j];
						array1[j] = array1[j+1];
						array1[j+1] = temp;
					}
				}
			}
		}
		System.out.println("Array 1; Array 2 ");
		for (int arpos = 0; arpos <= arlen-1; arpos += (1))
		{
			System.out.println((array1[arpos]) + (";         ") + (array2[arpos]));
		}
// 		Arrays.sort(array1); 
	}

}
