// Generated by Structorizer 3.32-34 

using System;

/// <summary>
/// </summary>
public class 04b_Celsius_und_fahrenheit_umrechner
{

	/// <param name="args"> array of command line arguments </param>
	public static void Main(string[] args)
	{

		// TODO: Check and accomplish variable declarations: 
		??? fortsetz;
		??? einheit;
		??? Temp;

		// TODO: You may have to modify input instructions, 
		//       possibly by enclosing Console.ReadLine() calls with 
		//       Parse methods according to the variable type, e.g.: 
		//          i = int.Parse(Console.ReadLine()); 

		do
		{
			Console.Write("Welche einheit wollen sie berechnen, Farenheit oder Celsius?"); , einheit = Console.ReadLine();
			switch (einheit)
			{
			case "F":
				Console.Write("Bitte gebe eine temperatur in grad Celsius ein"); Temp = Console.ReadLine();
				Console.Write("die temperatur von "); Console.Write(Temp); Console.Write("°C sind "); Console.Write(Temp+1.8+32); Console.WriteLine(" farenheit");
				break;
			case "C":
				Console.Write("Bitte gebe eine temperatur in Farenheit ein"); Temp = Console.ReadLine();
				Console.Write("die temperatur von "); Console.Write(Temp); Console.Write("F sind "); Console.Write((Temp-32)*5/9); Console.WriteLine(" °C");
				break;
			default:
				Console.WriteLine("Bitte gebe nur C (Für Celsius) oder F (Für Fahrenheit) an!");
			}
			Console.Write("Wollen sie fortführen? (J/N)"); fortsetz = Console.ReadLine();
		} while (! (fortsetz =="N"));
	}

}
