// Generated by Structorizer 3.32-34 

using System;

/// <summary>
/// </summary>
public class decimal_to_hex_calculator
{

	/// <param name="args"> array of command line arguments </param>
	public static void Main(string[] args)
	{

		// TODO: Check and accomplish variable declarations: 
		string x;
		string hex;

		// TODO: You may have to modify input instructions, 
		//       possibly by enclosing Console.ReadLine() calls with 
		//       Parse methods according to the variable type, e.g.: 
		//          i = int.Parse(Console.ReadLine()); 

		dec = Console.ReadLine();
		hex = "";
		if (dec == 0)
		{
			Console.WriteLine(0);
		}
		else
		{
			while (dec > 0)
			{
				??? shft = dec%16;
				switch (shft)
				{
				case 10:
					x = "A";
					break;
				case 11:
					x = "B";
					break;
				case 12:
					x = "C";
					break;
				case 13:
					x = "D";
					break;
				case 14:
					x = "E";
					break;
				case 15:
					x = "F";
					break;
				default:
					x = shft;
				}
				hex = x+hex;
				??? dec = dec/16;
			}
			Console.WriteLine(hex);
		}
	}

}
