// Generated by Structorizer 3.32-34 

using System;

/// <summary>
/// </summary>
public class 02_Averages
{

	/// <param name="args"> array of command line arguments </param>
	public static void Main(string[] args)
	{

		// TODO: Check and accomplish variable declarations: 
		int sum;
		??? number;
		??? amount;

		// TODO: You may have to modify input instructions, 
		//       possibly by enclosing Console.ReadLine() calls with 
		//       Parse methods according to the variable type, e.g.: 
		//          i = int.Parse(Console.ReadLine()); 

		Console.Write("how many numbers do you have?"); amount = Console.ReadLine();
		sum = 0;
		for (int i = 1; i <= amount; i += (1))
		{
			number = Console.ReadLine();
			sum = sum+number;
		}
		Console.Write("the avg is: "); Console.WriteLine(sum/amount);
	}

}
