// Generated by Structorizer 3.32-34 

using System;

/// <summary>
/// </summary>
public class 03_10h_Wahlberechtigung
{

	/// <param name="args"> array of command line arguments </param>
	public static void Main(string[] args)
	{

		// TODO: Check and accomplish variable declarations: 
		??? gjahr;
		// read date from device clock 
		int date;

		// TODO: You may have to modify input instructions, 
		//       possibly by enclosing Console.ReadLine() calls with 
		//       Parse methods according to the variable type, e.g.: 
		//          i = int.Parse(Console.ReadLine()); 

		Console.Write("Gebe dein geburtsjahr an"); gjahr = Console.ReadLine();
		// read date from device clock 
		date = 2026;
		if (date-gjahr > 18)
		{
			Console.WriteLine("Du bist wahlberechtigt");
		}
		else
		{
			Console.WriteLine("Du bist nicht wahlberechtigt");
		}
	}

}
