// Generated by Structorizer 3.32-34 

using System;

/// <summary>
/// </summary>
public class 01_26-02-09
{

	/// <param name="args"> array of command line arguments </param>
	public static void Main(string[] args)
	{

		// TODO: Check and accomplish variable declarations: 
		string X;

		X = "5";
		Console.WriteLine(X);
		for (int I = 0; I <= 1000; I += (1))
		{
			Console.WriteLine(I);
		}
	}

}
